name: Build Elixir docker container

branding:
  color: blue
  icon: anchor

description: >-
  GitHub Composite Action for building and optionally pushing Elixir & Beam
  based docker containers in an opinionated way.

inputs:
  build-args:
    description: >-
      (Optional) A list of extra build args to pass to the build step. Note
      that the github-token and hex-token will automatically be set if
      passed in.
    required: false
  cache:
    default: "true"
    description: >-
      (Optional) Enables caching built docker layers in the GitHub actions
      cache. This is highly recommended to speed up builds. Note, if you are
      not getting a speed bump, check your .dockerignore file to ensure you
      are not sending files that would break layer caching, like the .git
      folder.
    required: false
  context:
    default: "."
    description: >-
      (Optional) The build context to use when building the docker image.
    required: false
  file:
    default: Dockerfile
    description: >-
      (Optional) The path to the Dockerfile we are building.
    required: false
  github-token:
    default: ${{ github.token }}
    description: >-
      (Optional) Used to setup mix for pulling private packages from GitHub.
      This is usually `secrets.GH_PERSONAL_ACCESS_TOKEN`.
    required: false
  hex-organization:
    default: stord
    description: >-
      (Optional) Hex organization when authenticating. By default this will
      be the Stord hex organization.
    required: false
  hex-token:
    description: >-
      (Optional) Used to setup mix for pulling private packages from the
      hex organization. This is usually `secrets.HEX_API_KEY`.
    required: false
  images:
    description: >-
      (Optional) A list of docker images to use when building and
      publishing. By default, this will match the repository being built.
      For example, if you are building `stordco/test-app`, the image will
      be `ghcr.io/stordco/test-app`.
    required: false
  labels:
    description: >-
      (Optional) A list of labels to be added to the default ones when
      pushing the image.
    required: false
  oban-fingerprint:
    description: >-
      (Optional) Public key for fetching the oban pro repository data.
      This is usually refered to as OBAN_KEY_FINTERPRINT in documentation.
    required: false
  oban-token:
    description: >-
      (Optional) Oban pro license key.
    required: false
  platforms:
    default: linux/amd64
    description: >-
      (Optional) List of target platforms for build.
    required: false
  push:
    default: "false"
    description: >-
      (Optional) Push the final built image to the set registry.
    required: false
  secrets:
    description: >-
      (Optional) A list of extra secrets to pass to the build step. Note
      that the github-token and hex-token will automatically be set if
      passed in.
    required: false
  tags:
    description: >-
      (Optional) A list of tags to be added to the default ones when
      pushing the image.
    required: false

outputs:
  digest:
    description: >-
      The docker build image digest.
    value: ${{ steps.build.outputs.digest }}
  image:
    description: >-
      The first docker image published. This can be used as reference when
      deploying the image.
    value: ${{ steps.outputs.outputs.image }}
  images:
    description: >-
      A list of all the published docker images.
    value: ${{ steps.inputs.output.images }}
  labels:
    description: >-
      A list of all docker labels used when publishing.
    value: ${{ steps.metadata.outputs.labels }}
  metadata:
    description: >-
      The docker build result metadata
    value: ${{ steps.build.outputs.metadata }}
  tag:
    description: >-
      A sha specific tag used when publishing the docker image. This is the most
      specific tag that won't get repeated and should be used when deploying the
      image.
    value: ${{ steps.outputs.outputs.tag }}
  tags:
    description: >-
      A list of all docker tags that were published.
    value: ${{ steps.metadata.outputs.tags }}

runs:
  using: composite
  steps:
    - id: inputs
      name: Get Inputs
      uses: actions/github-script@v6
      env:
        INPUT_BUILD_ARGS: ${{ inputs.build-args }}
        INPUT_CACHE: ${{ inputs.cache }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_HEX_TOKEN: ${{ inputs.hex-token }}
        INPUT_IMAGES: ${{ inputs.images }}
        INPUT_OBAN_FINGERPRINT: ${{ inputs.oban-fingerprint }}
        INPUT_OBAN_TOKEN: ${{ inputs.oban-token }}
        INPUT_SECRETS: ${{ inputs.secrets }}
      with:
        script: |
          const buildArgs = core.getMultilineInput('build args')
          const secrets = core.getMultilineInput('secrets')

          buildArgs.push(`GIT_SHA=${context.sha}`)

          const githubToken = core.getInput('github token')
          if (githubToken != null && githubToken !== '') {
            buildArgs.push(`GH_PERSONAL_ACCESS_TOKEN=${githubToken}`)
            buildArgs.push(`GITHUB_PERSONAL_ACCESS_TOKEN=${githubToken}`)
            secrets.push(`github_token=${githubToken}`)
            core.info('Added GitHub token build information')
          }

          const hexToken = core.getInput('hex token')
          if (hexToken != null && hexToken !== '') {
            buildArgs.push(`HEX_TOKEN=${hexToken}`)
            secrets.push(`hex_token=${hexToken}`)
            core.info('Added Hex token build information')
          }

          const obanFingerprint = core.getInput('oban fingerprint')
          const obanToken = core.getInput('oban token')
          if (obanFingerprint != null && obanFingerprint !== '') {
            if (obanToken != null && obanToken !== '') {
              secrets.push(`oban_fingerprint=${obanFingerprint}`)
              secrets.push(`oban_token=${obanToken}`)
              core.info('Added Oban Pro build information')
            }
          }

          core.setOutput('build-args', buildArgs.join('\n'))
          core.setOutput('secrets', secrets.join('\n'))

          if (core.getBooleanInput('cache')) {
            core.setOutput('cache-from', 'type=gha')
            core.setOutput('cache-to', 'type=gha,mode=max')
            core.info('Using GitHub cache for maximum performance')
          } else {
            core.setOutput('cache-from', '')
            core.setOutput('cache-to', '')
            core.info('Cache is disabled')
          }

          const images = core.getMultilineInput('images')
          if (images.length > 0) {
            core.setOutput('images', process.env.INPUT_IMAGES)
          } else {
            const image = `ghcr.io/${context.repo.owner}/${context.repo.repo}`
            core.setOutput('images', image)
            core.info(`Setting docker image to default ${image}`)
          }

    - id: metadata
      name: Get Metadata
      uses: docker/metadata-action@v5
      with:
        flavor: |
          latest=auto
        github-token: ${{ inputs.github-token }}
        images: |
          ${{ steps.inputs.outputs.images }}
        labels: |
          ${{ inputs.labels }}
        tags: |
          type=sha
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=ref,event=branch
          type=ref,event=pr
          ${{ inputs.tags }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - id: build
      name: Build
      uses: docker/build-push-action@v4
      with:
        build-args: ${{ steps.inputs.outputs.build-args }}
        cache-from: ${{ steps.inputs.outputs.cache-from }}
        cache-to: ${{ steps.inputs.outputs.cache-to }}
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        labels: ${{ steps.metadata.outputs.labels }}
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push }}
        secrets: ${{ steps.inputs.outputs.secrets }}
        tags: ${{ steps.metadata.outputs.tags }}

    - id: outputs
      name: Get Outputs
      uses: actions/github-script@v6
      env:
        BUILD_OUTPUT: ${{ steps.metadata.outputs.json }}
      with:
        script: |
          const metadata = JSON.parse(process.env.BUILD_OUTPUT)
          const shaUrl = metadata.tags.find((t) => t.includes(':sha-'))

          if (shaUrl == null) {
            core.error('Unable to find sha tag of image')
          } else {
            const [image, tag] = shaUrl.split(':')
            core.setOutput('image', image)
            core.setOutput('tag', tag)
          }
