name: actions-elixir/setup

branding:
  color: blue
  icon: list

description: >-
  GitHub Composite Action for installing Elixir & Beam, setting up and
  retrieving dependencies along with caching.

inputs:
  cache_path:
    default: |
      _build
      deps
    description: Override default paths to cache
    type: string
  elixir_version:
    description: Elixir version (ex: 1.13.4)
    required: true
    type: string
  github_personal_access_token:
    default: null
    description: >-
      (Optional) Used to set git up for mix dep retrieval from private repos,
      usually `secrets.GITHUB_PERSONAL_ACCESS_TOKEN`
    type: string
  otp_version:
    description: OTP version (ex: "25.0")
    required: true
    type: string

runs:
  steps:
      - name: Install (Elixir)
        id: beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ inputs.otp_version }}
          elixir-version: ${{ inputs.elixir_version }}

      - name: Cache
        id: cache
        uses: actions/cache@v2
        with:
          key: elixir-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-credo-${{ hashFiles('mix.lock') }}-${{ github.ref }}
          restore-keys: |
            elixir-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-credo-${{ hashFiles('mix.lock') }}-refs/heads/${{ github.event.repository.default_branch }}
            elixir-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-credo-${{ hashFiles('mix.lock') }}-
            elixir-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-credo-
            elixir-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-
          path: ${{ inputs.cache_path }}

      - name: Setup (Mix)
        if: inputs.github_personal_access_token != null
        run: |
          # git config - add GitHub token
          git \
            config \
            --global \
            url."https://${{ inputs.github_personal_access_token }}:@github.com".insteadOf \
            "https://github.com"
        shell: bash

      - name: Install (Mix)
        if: steps.cache.outputs.cache-hit != 'true'
        run: mix deps.get
        shell: bash
  using: composite
