name: actions-elixir//setup

branding:
  color: blue
  icon: list

description: >-
  GitHub Composite Action for installing Elixir & Beam, setting up and
  retrieving dependencies along with caching.

inputs:
  cache_path:
    default: |
      _build
      deps
    description: Override default paths to cache
    type: string
  elixir-version:
    type: string
  github_personal_access_token:
    default: null
    description: (Optional) Usually `secrets.GITHUB_PERSONAL_ACCESS_TOKEN`, to setup git for mix dep retrieval
    type: string
  otp-version:
    type: string



runs:
  using: composite
  steps:
      - name: Install (Elixir)
        id: beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ inputs.otp-version }}
          elixir-version: ${{ inputs.elixir-version }}

      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          key: elixir-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-credo-${{ hashFiles('mix.lock') }}-${{ github.ref }}
          restore-keys: |
            elixir-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-credo-${{ hashFiles('mix.lock') }}-refs/heads/main
            elixir-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-credo-${{ hashFiles('mix.lock') }}-
            elixir-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-credo-
            elixir-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-
          path: ${{ inputs.cache_path }}

      - name: Setup (Mix)
        if: inputs.github_personal_access_token != null
        run: |
          # git config - setup for mix
          git config --global url."https://${{ inputs.github_personal_access_token }}:@github.com".insteadOf "https://github.com"
        shell: bash

      - name: Install (Mix)
        if: steps.cache.outputs.cache-hit != 'true'
        run: mix deps.get
        shell: bash
